---
# tasks/main.yml
- name: Install iRODS package repository signing key
  ansible.builtin.apt_key:
    url: https://packages.irods.org/irods-signing-key.asc

- name: Install iRODS repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/renci-irods.list
    mode: u+rw
    content: |
      deb [arch=amd64] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main
