---
# tasks/main.yml
- name: Install iRODS package repository signing key
  ansible.builtin.apt_key:
    url: https://packages.irods.org/irods-signing-key.asc

- name: Install iRODS repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/renci-irods.list
    mode: u+rw
    content: |
      deb [arch=amd64] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main

# Update apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes


# Lock iRODS packages to the specified version
- name: Lock iRODS packages to required version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/irods
    mode: u+rw
    content: |
      Package: irods-resource-*
      Pin: version {{ irods_version }}*
      Pin-Priority: 1001

      Package: irods-*
      Pin: version {{ irods_version }}*
      Pin-Priority: 1001


# Install iRODS server with a specific version
- name: Install iRODS server with specific version
  ansible.builtin.apt:
    name: "irods-server"
    state: present

# Install iRODS PostgreSQL database plugin with a specific version
- name: Install iRODS PostgreSQL database plugin with specific version
  ansible.builtin.apt:
    name: "irods-database-plugin-postgres"
    state: present


################################################

# Check if the ODBC driver is already installed
- name: Check if ODBC driver is installed
  ansible.builtin.stat:
    path: /usr/lib/odbc/odbcinst.ini
  register: odbc

# Create setup configuration file if ODBC is not installed
- name: Create setup configuration file
  when: not odbc.stat.exists
  ansible.builtin.template:
    src: setup_configuration.json.j2
    dest: /tmp/setup_configuration.json
    mode: u+rw

# Initialize ICAT schema
- name: Initialize ICAT schema
  when: not odbc.stat.exists
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o errexit
      python3 /var/lib/irods/scripts/setup_irods.py --stdout --test --verbose \
        --json_configuration_file=/tmp/setup_configuration.json
      rm --force /var/lib/irods/log/test_mode_output.log /tmp/setup_configuration.json || true
  register: response
  changed_when: response.stdout is search('Updating to schema version')
