---
# tasks/main.yml
- name: Install iRODS package repository signing key
  ansible.builtin.apt_key:
    url: https://packages.irods.org/irods-signing-key.asc

- name: Install iRODS repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/renci-irods.list
    mode: u+rw
    content: |
      deb [arch=amd64] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main

# Update apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes


# Lock iRODS packages to the specified version
- name: Lock iRODS packages to required version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/irods
    mode: u+rw
    content: |
      Package: irods-resource-*
      Pin: version {{ irods_version }}*
      Pin-Priority: 1001

      Package: irods-*
      Pin: version {{ irods_version }}*
      Pin-Priority: 1001


# Install iRODS server with a specific version
- name: Install iRODS server with specific version
  ansible.builtin.apt:
    name: "irods-server"
    state: present

# Install iRODS PostgreSQL database plugin with a specific version
- name: Install iRODS PostgreSQL database plugin with specific version
  ansible.builtin.apt:
    name: "irods-database-plugin-postgres"
    state: present

- name: Ensure iRODS does attempts to start on boot
  ansible.builtin.service:
    name: irods
    enabled: true

- name: Create service group
  ansible.builtin.group:
    name: "{{ _irods_service_group_name }}"
    system: true

- name: Create service account
  ansible.builtin.user:
    name: "{{ _irods_service_account_name }}"
    system: true
    home: /var/lib/irods
    createhome: true
    group: "{{ _irods_service_group_name }}"
    groups: tty
    shell: /bin/bash
    comment: iRODS Administrator