---
- name: Install iRODS Repository on all hosts of irods
  hosts: irods
  become: true
  roles:
    - provision
  tasks:
    - name: Ensure iRODS ownership
      include_tasks: roles/provision/permissions/ensure_irods_ownership.yml

- name: Update /etc/hosts
  ansible.builtin.import_playbook: update_hosts.yml

- name: Configure iRODS
  import_playbook: cfg_irods.yml

- name: Provision Catalog
  ansible.builtin.import_playbook: catalog.yml

- name: Provision Resource
  ansible.builtin.import_playbook: resource.yml
