---
- name: Install iRODS Repository on ICAT Server
  hosts: irods
  become: true
  roles:
    - provision

  tasks:
    - name: Ensure iRODS ownership
      include_tasks: roles/provision/permissions/ensure_irods_ownership.yml

- name: Configure iRODS
  import_playbook: cfg_irods.yml

- name: Ensure catalog service providers are started
  hosts: irods_catalog
  become: "{{ _become_svc_acnt }}"
  become_user: "{{ _irods_service_account_name }}"
  tasks:
    - name: Start iRODS
      irods_ctl:
