---
- name: Install iRODS Repository on ICAT Server
  hosts: irods
  become: true
  roles:
    - provision

  tasks:
    - name: Ensure iRODS ownership
      include_tasks: roles/provision/permissions/ensure_irods_ownership.yml

- name: Configure iRODS
  import_playbook: cfg_irods.yml
