---
- name: Install iRODS Repository on ICAT Server
  hosts: irods
  become: true
  roles:
    - provision

- name: Ensure iRODS ownership
  ansible.builtin.import_tasks: tasks/ensure_irods_ownership.yml

- name: Configure iRODS
  import_playbook: cfg_irods.yml
