---
- name: Ensure de-irods user exists
  delegate_to: localhost
  become: false
  irods_user:
    name: de-irods
    password: "{{ de_irods_password }}"
    state: present
    host: "{{ groups['irods_catalog'][0] }}"
    port: "{{ _irods_zone_port }}"
    admin_user: "{{ _irods_clerver_user }}"
    admin_password: "{{ _irods_clerver_password }}"
    zone: "{{ _irods_zone_name }}"

